services:
  laravel.app:
    build:
      # context: ./vendor/laravel/sail/runtimes/8.3
      # dockerfile: Dockerfile
      context: ./
      dockerfile: Dockerfile

    image: my_new_app:latest # Custom image name and tag
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8099}:80"
      - "${VITE_PORT:-5176}:${VITE_PORT:-5173}"
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      PHP_MEMORY_LIMIT: 512M
    volumes:
      - ".:/var/www/html"
    networks:
      - app-network
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: "postgres:15"
    container_name: my_new_app-postgres # Custom container name
    ports:
      - "${FORWARD_DB_PORT:-54329}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "app-pgsql:/var/lib/postgresql/data"
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    container_name: my_new_app-redis # Custom container name
    ports:
      - "${FORWARD_REDIS_PORT:-63790}:6379"
    volumes:
      - "app-redis:/data"
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  app-network:
    driver: bridge
volumes:
  app-pgsql:
    driver: local
  app-redis:
    driver: local
